"""Added users table

Revision ID: 64c654834385
Revises: 16b4a8c6eb67
Create Date: 2022-10-25 23:49:00.956269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64c654834385'
down_revision = '16b4a8c6eb67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_table('failed_jobs')
    op.drop_table('websockets_statistics_entries')
    op.drop_table('chess_boards')
    op.drop_index('chess_definitions_piece_type_is_white_index', table_name='chess_definitions')
    op.drop_table('chess_definitions')
    op.drop_table('tiles')
    op.drop_index('personal_access_tokens_tokenable_type_tokenable_id_index', table_name='personal_access_tokens')
    op.drop_table('personal_access_tokens')
    op.drop_table('slur')
    op.drop_index('password_resets_email_index', table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index('ix_items_id', table_name='items')
    op.drop_index('ix_items_title', table_name='items')
    op.drop_table('items')
    op.drop_table('migrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('migration', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('batch', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='migrations_pkey')
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_index('ix_items_title', 'items', ['title'], unique=False)
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    op.create_table('password_resets',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True)
    )
    op.create_index('password_resets_email_index', 'password_resets', ['email'], unique=False)
    op.create_table('slur',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('needle', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='slur_pkey')
    )
    op.create_table('personal_access_tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tokenable_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tokenable_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('abilities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='personal_access_tokens_pkey'),
    sa.UniqueConstraint('token', name='personal_access_tokens_token_unique')
    )
    op.create_index('personal_access_tokens_tokenable_type_tokenable_id_index', 'personal_access_tokens', ['tokenable_type', 'tokenable_id'], unique=False)
    op.create_table('tiles',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('piece_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_white', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tiles_pkey')
    )
    op.create_table('chess_definitions',
    sa.Column('piece_type', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('is_white', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('representation', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('representation', name='chess_definitions_representation_unique')
    )
    op.create_index('chess_definitions_piece_type_is_white_index', 'chess_definitions', ['piece_type', 'is_white'], unique=False)
    op.create_table('chess_boards',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=False),
    sa.Column('board_start', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('white_turn', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chess_boards_pkey')
    )
    op.create_table('websockets_statistics_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('peak_connection_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('websocket_message_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('api_message_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='websockets_statistics_entries_pkey')
    )
    op.create_table('failed_jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('connection', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('queue', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('exception', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('failed_at', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='failed_jobs_pkey'),
    sa.UniqueConstraint('uuid', name='failed_jobs_uuid_unique')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
