"""empty message

Revision ID: 722dcd565233
Revises: 
Create Date: 2022-10-28 21:02:52.865944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722dcd565233'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_addresses_id'), 'house_addresses', ['id'], unique=False)
    op.create_table('house_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('lad', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house_addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_points_id'), 'house_points', ['id'], unique=False)
    op.drop_index('ix_house_adresses_id', table_name='house_adresses')
    op.drop_table('house_adresses')
    op.drop_index('ix_items_id', table_name='items')
    op.drop_index('ix_items_title', table_name='items')
    op.drop_table('items')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_constraint('house_apartments_house_id_fkey', 'house_apartments', type_='foreignkey')
    op.create_foreign_key(None, 'house_apartments', 'house_addresses', ['house_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'house_apartments', type_='foreignkey')
    op.create_foreign_key('house_apartments_house_id_fkey', 'house_apartments', 'house_adresses', ['house_id'], ['id'])
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='items_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_index('ix_items_title', 'items', ['title'], unique=False)
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    op.create_table('house_adresses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='house_adresses_pkey'),
    sa.UniqueConstraint('address', name='house_adresses_address_key')
    )
    op.create_index('ix_house_adresses_id', 'house_adresses', ['id'], unique=False)
    op.drop_index(op.f('ix_house_points_id'), table_name='house_points')
    op.drop_table('house_points')
    op.drop_index(op.f('ix_house_addresses_id'), table_name='house_addresses')
    op.drop_table('house_addresses')
    # ### end Alembic commands ###
