"""empty message

Revision ID: 7ba38afff2ff
Revises: 722dcd565233
Create Date: 2022-10-28 21:07:56.289496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba38afff2ff'
down_revision = '722dcd565233'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_addresses_id'), 'house_addresses', ['id'], unique=False)
    op.create_table('house_apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartments', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house_addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_apartments_id'), 'house_apartments', ['id'], unique=False)
    op.create_table('house_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('lad', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house_addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_points_id'), 'house_points', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_house_points_id'), table_name='house_points')
    op.drop_table('house_points')
    op.drop_index(op.f('ix_house_apartments_id'), table_name='house_apartments')
    op.drop_table('house_apartments')
    op.drop_index(op.f('ix_house_addresses_id'), table_name='house_addresses')
    op.drop_table('house_addresses')
    # ### end Alembic commands ###
